version: '3.3'
services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
    - db_data:/var/lib/postgresql/data
  backend:
    container_name: backend
    depends_on:
      - db
    build: ../backend/foodgram
    env_file: .env
    volumes:
      - backend_static:/app/backend_static
      - backend_media:/app/media 
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static/
      - backend_media:/backend_media/ 

volumes:
  db_data:
  backend_static:
  backend_media:
