# Generated by Django 3.2.16 on 2025-05-30 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="unique_ingredient_in_recipe",
        ),
    ]
