# Generated by Django 3.2.16 on 2025-06-01 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_auto_20250531_2036"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "verbose_name": "Данные о подписках",
                "verbose_name_plural": "Данные о подписках",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецепте",
            },
        ),
    ]
