# Generated by Django 3.2.16 on 2025-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
