# Generated by Django 3.2.16 on 2025-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250531_2036'),
        ('users', '0002_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
    ]
