# Generated by Django 3.2.16 on 2025-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_auto_20250601_2112"),
        ("users", "0004_auto_20250601_0259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="shopping_cart",
            field=models.ManyToManyField(
                blank=True, related_name="who_added_to_cart", to="recipes.Recipe"
            ),
        ),
    ]
